<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <title>Choosing a Control Group in a RCT with Multiple Treatment Periods</title>
  <meta property="og:title" content="Choosing a Control Group in a RCT with Multiple Treatment Periods" />
  <meta name="twitter:title" content="Choosing a Control Group in a RCT with Multiple Treatment Periods" />
  <meta name="description" content="Came across a fun little problem over the past few weeks that is related to the topic of policy impact evaluation - a long time interest of mine! Here’s the setting: we have a large population of individuals and a number of treatments that we want to gauge the effectiveness of. The treatments are not necessarily the same but are targeted towards certain sub-segments in the population. Examples of such situations include online ad targeting or marketing campaigns.">
  <meta property="og:description" content="Came across a fun little problem over the past few weeks that is related to the topic of policy impact evaluation - a long time interest of mine! Here’s the setting: we have a large population of individuals and a number of treatments that we want to gauge the effectiveness of. The treatments are not necessarily the same but are targeted towards certain sub-segments in the population. Examples of such situations include online ad targeting or marketing campaigns.">
  <meta name="twitter:description" content="Came across a fun little problem over the past few weeks that is related to the topic of policy impact evaluation - a long time interest of mine! Here’s the setting: we have a large population of …">
  <meta name="author" content="Timothy Lin"/>
  <meta name="twitter:card" content="summary" />
  <meta property="og:url" content="https://www.timlrx.com/2017/11/18/choosing-a-control-group-in-a-rct-with-multiple-treatment-periods/" />
  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="Quasilinear Musings" />

  <meta name="generator" content="Hugo 0.30.2" />
  <link rel="canonical" href="https://www.timlrx.com/2017/11/18/choosing-a-control-group-in-a-rct-with-multiple-treatment-periods/" />
  <link rel="alternate" href="https://www.timlrx.com/index.xml" type="application/rss+xml" title="Quasilinear Musings">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css" integrity="sha384-wITovz90syo1dJWVh32uuETPVEtGigN07tkttEqPv+uR2SE/mbQcG7ATL28aI9H0" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="https://www.timlrx.com/css/main.css" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" />
  <link rel="stylesheet" href="https://www.timlrx.com/css/pygment_highlights.css" />
  <link rel="stylesheet" href="https://www.timlrx.com/css/highlight.min.css" />



<script>
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', 'UA-100201704-1', 'auto');
ga('send', 'pageview');
</script>
<script async src='//www.google-analytics.com/analytics.js'></script>

</head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top navbar-custom">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="https://www.timlrx.com/">Quasilinear Musings</a>
    </div>

    <div class="collapse navbar-collapse" id="main-navbar">
      <ul class="nav navbar-nav navbar-right">
        
          
            <li>
              <a title="Blog" href="../../../../post/">Blog</a>
            </li>
          
        
          
            <li>
              <a title="About" href="../../../../about/">About</a>
            </li>
          
        
          
            <li>
              <a title="SG-Dashboard" href="../../../../dashboard/sg-dashboard/">SG-Dashboard</a>
            </li>
          
        
          
            <li>
              <a title="Resources" href="../../../../resources/">Resources</a>
            </li>
          
        
          
            <li>
              <a title="Tags" href="../../../../tags">Tags</a>
            </li>
          
        

        

        
      </ul>
    </div>

    <div class="avatar-container">
      <div class="avatar-img-border">
        
      </div>
    </div>

  </div>
</nav>




    
  
  
  




  

  <header class="header-section ">
    
    <div class="intro-header no-img">
      
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="post-heading">
              <h1>Choosing a Control Group in a RCT with Multiple Treatment Periods</h1>
                
                
                  <span class="post-meta">
  Posted on November 18, 2017
  
</span>


                
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>


    
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <article role="main" class="blog-post">
        <p>Came across a fun little problem over the past few weeks that is related to the topic of policy impact evaluation - a long time interest of mine! Here’s the setting: we have a large population of individuals and a number of treatments that we want to gauge the effectiveness of. The treatments are not necessarily the same but are targeted towards certain sub-segments in the population. Examples of such situations include online ad targeting or marketing campaigns. This gives rise to the following 3 methods of selecting the treatment and control groups:</p>
<ol style="list-style-type: decimal">
<li><p>Apply the targeting rule to get a population subset. Split this group into treatment and control, run the treatment and collect the results. In the next time period, keep those which remain in the control as the control and top up the group with a random sample to maintain a similar proportion of treated and control individuals.</p></li>
<li><p>Randomly split the population into treatment and control. For each period, do not vary the control group. Just administer the treatment on the treatment group. Evaluate the effectiveness of each period on the control group applying the targeting rule to subset the relevant control population.</p></li>
<li><p>For each period and campaign, apply the targeting rule and randomise the group into treatment and control.</p></li>
</ol>
<div id="framework" class="section level3">
<h3>Framework</h3>
<p>Would these methods give equivalent results? I will use the Neyman-Rubin causal framework to formalise the intended goal and outcomes. Let <span class="math inline">\(Y_{i}\)</span> denote the outcome of an individual (e.g. total spending). The fundamental problem of inference is that one would never be able to observe the spending of an individual if he was administered the treatment <span class="math inline">\(Y_{1i}\)</span> or if he was not <span class="math inline">\(Y_{0i}\)</span>. Here, <span class="math inline">\(Y_{1i}\)</span> and <span class="math inline">\(Y_{0i}\)</span> are referred to as potential outcomes as only one outcome can be observed but not the other.</p>
<p>The average effect of a treatment on an individual is given by:
<span class="math display">\[
E[Y_{1i} - Y_{0i}]
\]</span></p>
<p>Let <span class="math inline">\(D_{i}=1\)</span> denote being treated and <span class="math inline">\(D_{i}=0\)</span> being not treated. We can look at the difference in average outcomes based on treatment status:
<span class="math display">\[
E[Y_{i} \vert D_{i}=1] - E[Y_{i} \vert D_{i}=0] = E[Y_{1i} \vert D_{i}=1] - E[Y_{0i} \vert D_{i}=0]
\]</span></p>
<p>If the treatment is not randomly assigned (e.g. people can choose to take-up the treatment), the above expression can be written as:
<span class="math display">\[
\begin{aligned}
E[Y_{i} \vert D_{i}=1] - E[Y_{i} \vert D_{i}=0] &amp;= E[Y_{1i} \vert D_{i}=1] - E[Y_{0i} \vert D_{i}=1]   \\
&amp;+ E[Y_{0i} \vert D_{i}=1] - E[Y_{0i} \vert D_{i}=0]
\end{aligned}
\]</span>
The first term on the right is the average treatment effect on treated while the second is the selection bias. For example, if the advertisement has a positive impact on spending then we would expect the second term to be positive leading to an upward bias in its estimated effect.</p>
<p>And that’s precisely why to evaluate the effectiveness of a treatment, we have to randomise people into treatment and control groups. Under randomisation, the potential outcomes are independent of the treatment<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>,
<span class="math display">\[
\{Y_{1i}, Y_{0i}\} \perp D_{i} 
\]</span>
and</p>
<p><span class="math display">\[
E[Y_{1i} \vert D_{i}=1] - E[Y_{0i} \vert D_{i}=0] = E[Y_{1i} - Y_{0i}]
\]</span>
This implies that taking the difference between the average across the treated and control group will give us the <em>Average Treatment Effect (ATE)</em>. In many situations, we relax the assumption by only allowing the mean of non-treated individuals to be independent of treatment status:</p>
<p><span class="math display">\[
E[Y_{1i} \vert D_{i}=1] - E[Y_{0i} \vert D_{i}=0] = E[Y_{1i} - Y_{0i} \vert D_{i}=1]
\]</span>
This gives the <em>Average Treatment on Treated (ATT)</em>.</p>
</div>
<div id="thought-experiment" class="section level3">
<h3>Thought Experiment</h3>
<p>To consider the various scenarios outlined above, let me setup a little thought experiment. In my world, there are two types of customers, high type or low type, which I denote by <span class="math inline">\(X_{i}\)</span>. Low type customers, <span class="math inline">\(X_{i} = L\)</span>, spend <span class="math inline">\(\alpha + \epsilon_{it}\)</span> dollars while high type customers, <span class="math inline">\(X_{i} = H\)</span>, spend <span class="math inline">\(\alpha + \beta + \epsilon_{it}\)</span> dollars, where <span class="math inline">\(\epsilon_{it}\)</span> is a drawn from a normal distribution. The treatment of interest is a marketing promotion which is targeted at high spending individuals. Assume low type customers are not affected by the marketing promotion while high type customers have a <span class="math inline">\(p\%\)</span> probability of spending an additional <span class="math inline">\(\delta\)</span> dollars which persist for the rest of the periods. Having taken up the treatment, the high type individual will no longer subscribe to future promotions. I ignore any changes in spending across time periods, though in practice one way to account for such changes is to consider the first difference.</p>
</div>
<div id="simulation-setup" class="section level3">
<h3>Simulation Setup</h3>
<p>To check on the effectiveness of the 3 methods of selecting a control group, let’s do a little simulation with the following parameters:
<span class="math display">\[
\begin{aligned}
\alpha &amp;= 3, \\
\beta &amp;=2,   \\
\delta &amp;=1, \\
p &amp;=0.3, \\ 
\epsilon_{it} &amp;\sim N(0,1) ~\forall i 
\end{aligned}
\]</span></p>
<p>To start, let’s build a 3 period model with 100,000 people in the population (half high type and half low type). I consider observations in 3 period, <span class="math inline">\(t=1,2,3\)</span> and split the population into 80% treatment and 20% control. The treatment is targeted towards higher spending individuals. However, one cannot observe the underlying type distribution and has to segment the population by the amount which they spend. In the simulation, I use a spending rule (<span class="math inline">\(Y_{i} &gt; 4\)</span>), which covers approximately 50% of the initial population.</p>
<pre class="r"><code>n= 1e5
p = 0.3
d = 1

df = data.frame(ind = seq(1, n),
                type = rep(c(0,1), n/2),
                epsilon = rnorm(n, 0, 1),
                unif = runif(n, 0, 1),
                unif2 = runif(n, 0, 1))

df$spend = ifelse(df$type==0, 3, 5) + df$epsilon

### Select treatment and control using unif
df$target = ifelse(df$spend&gt;4 , 1, 0)
df$treat = ifelse(df$target==1 &amp; df$unif&lt;0.8, 1, 0)
df$control = ifelse(df$target==1 &amp; df$unif&gt;=0.8, 1, 0)</code></pre>
</div>
<div id="att" class="section level3">
<h3>ATT</h3>
<p>Despite covering 50% of the population, randomness in spending patterns implies that the target group would still consist of both low and high types. This means that the outcome of our experiment would only yield an ATT effect, or the effect on the sub-population who spend more than 4. Let us calculate this effect before using the simulation to verify the results. We are interested in finding the fraction of population who are high type conditional on spending more than 4. First, let us calculate the probability that a high and low type individual spend more than 4 using r’s pnorm function before calculating the conditional probability:</p>
<pre class="r"><code>1-pnorm(4, 3, 1)</code></pre>
<pre><code>## [1] 0.1586553</code></pre>
<pre class="r"><code>1-pnorm(4, 5, 1)</code></pre>
<pre><code>## [1] 0.8413447</code></pre>
<p><span class="math display">\[
\begin{aligned}
P(X_{i}=H \vert Y_{i}&gt;4) &amp;= \frac{P(X_{i}=H, Y_{i}&gt;4)}{P(Y_{i} &gt;4)} \\
&amp;= \frac{0.841*0.5}{0.159*0.5 + 0.841 *0.5} \\
&amp;= 0.841
\end{aligned}
\]</span>
Since only 0.841 of the sub-population would be affected by the treatment, we would expect that the average treatment effect would be <span class="math inline">\(0.841*0.3 = 0.25\%\)</span></p>
<pre class="r"><code>### Add in treatment effect to treated
df$delta = ifelse(df$treat==1 &amp; df$type==1 &amp; runif(n, 0, 1)&lt;=p, d, 0)
df$spend2 = df$delta + df$spend

### Average treatment effect on treated
df_subset = df[df$target==1,]
mean(df[df$treat==1,]$spend2) - mean(df[df$control==1,]$spend2)</code></pre>
<pre><code>## [1] 0.2534045</code></pre>
<pre class="r"><code>lm(spend2 ~ treat, data=df_subset)</code></pre>
<pre><code>## 
## Call:
## lm(formula = spend2 ~ treat, data = df_subset)
## 
## Coefficients:
## (Intercept)        treat  
##      5.1672       0.2534</code></pre>
<p>More generally, a better approach to check our result would be to loop over many random samples and find the central tendency of the parameter estimate:</p>
<pre class="r"><code>att &lt;- function(n=1e5, p=0.3, d=1){
  df = data.frame(ind = seq(1, n),
                  type = rep(c(0,1), n/2),
                  epsilon = rnorm(n, 0, 1),
                  unif = runif(n, 0, 1),
                  unif2 = runif(n, 0, 1))
  df$spend = ifelse(df$type==0, 3, 5) + df$epsilon
  
  ### Select treatment and control using unif
  df$target = ifelse(df$spend&gt;4 , 1, 0)
  df$treat = ifelse(df$target==1 &amp; df$unif&lt;0.8, 1, 0)
  df$control = ifelse(df$target==1 &amp; df$unif&gt;=0.8, 1, 0)
  ### Add in treatment effect to treated
  df$delta = ifelse(df$treat==1 &amp; df$type==1 &amp; runif(n, 0, 1)&lt;=p, d, 0)
  df$spend2 = df$delta + df$spend
  ### Average treatment effect on treated
  df_subset = df[df$target==1,]
  mean(df[df$treat==1,]$spend2) - mean(df[df$control==1,]$spend2)
  mod &lt;- lm(spend2 ~ treat, data=df_subset)
  return(coef(mod)[&quot;treat&quot;])
}

B = 500
coef_list = list()
for(b in 1:B){
  coef_list[[b]] &lt;- att()
}

hist(unlist(coef_list))</code></pre>
<p><img src="../../../../post/2017-11-18-choosing-a-control-group-in-a-rct-with-multiple-treatment-periods_files/figure-html/attrepeat-1.png" width="672" /></p>
<pre class="r"><code>mean(unlist(coef_list))</code></pre>
<pre><code>## [1] 0.2526948</code></pre>
<p>Unsurprisingly, the empirical results tally with our mathematical derivation.</p>
</div>
<div id="nd-period-att" class="section level3">
<h3>2nd period ATT</h3>
<p>Now, we are ready to evaluate the various proposed control groups. To keep things simple, the 2nd marketing promotion will be the same as the first and target individuals who spend above 4. However, this time to evaluate the results we need to consider 3 groups - low type, high type takers and high type non-takers - where takers and non-takers refer to whether they responded positively to the treatment in the first period. Repeating the above calculations and focusing on the share of non-takers in the sub-population:
<span class="math display">\[
\begin{aligned}
P(X_{i,t=2}=H_{nt} \vert Y_{i,t=2}&gt;4) &amp;= P(X_{i,t=2}=H_{nt} \vert Y_{i,t=2}&gt;4, i \in treated_{t=1}) + P(X_{i,t=2}=H_{nt} \vert Y_{i,t=2}&gt;4, i \in control_{t=1})\\
&amp;=\frac{P(X_{i,t=2}=H_{nt}, Y_{i,t=2}&gt;4)}{P(Y_{i,t=2} &gt;4)}*0.8 + 0.841*0.2 \\
&amp;= \frac{0.841*0.5*0.7}{0.159*0.5 + 0.841 *0.5*0.7 + + 0.841 *0.5*0.3} *0.8 + 0.841*0.2\\
&amp;= 0.639 \\
\\
ATT_{t=2} &amp;= 0.639*0.3  \\
&amp;= 0.192
\end{aligned}
\]</span>
The calculations make intuitive sense. With a smaller pool of customers who would respond positively to the treatment, the ATT in the second period is lower than the first.</p>
</div>
<div id="targeting-rule-with-top-up" class="section level3">
<h3>Targeting rule with top-up</h3>
<p>Here’s a few lines of code to implement the idea of trying to keep the members of the control group relatively similar and do a random top-up where necessary.</p>
<pre class="r"><code>### 2nd time period
df$target2 = ifelse(df$spend2&gt;4, 1, 0)
n_control2 = round(sum(df$target2) * 0.2)
n_control_remain = sum(df$target2 &amp; df$control==1)
unif_threshold = (n_control2 - n_control_remain) / (sum(df$target2) - n_control_remain)
df$control2 = ifelse(df$target2==1 &amp; (df$control==1 | df$unif2&lt;=unif_threshold), 1, 0)
### Approximately fill up
df$treat2 = ifelse(df$target2==1 &amp; df$control2==0, 1, 0)
df$delta2 = ifelse(df$treat2==1 &amp; df$type==1 &amp; df$delta==0 &amp; runif(n, 0, 1)&lt;=p, d, 0)
df$spend3 = df$delta2 + df$spend2  + rnorm(n,0,1)

### Average treatment effect 2 (Less than predicted!)
df_subset2 = df[df$target2==1,]
lm(spend3 ~ treat2, data=df_subset2)</code></pre>
<p>I show the results from 500 runs of the above code extracting the coefficient of the supposed treatment effect as well as the proportion of high non-treated individuals from the treatment and control group.</p>
<pre class="r"><code>mean(unlist(coef_list))</code></pre>
<pre><code>## [1] 0.4276794</code></pre>
<pre class="r"><code>mean(unlist(prop_control_list))</code></pre>
<pre><code>## [1] 0.8404415</code></pre>
<pre class="r"><code>mean(unlist(prop_treat_list))</code></pre>
<pre><code>## [1] 0.5890693</code></pre>
<p>Notice that the proportion of high non-treated individuals are no longer the same across the groups and the estimated effect is much larger than the calculated value. Almost no one has been treated in the control group. This leads to an upwards bias in the estimated treatment effect since the coefficient estimate is combining the effect of both the first and second treatment together.</p>
<p>More generally, the extent and direction of bias cannot be so easily quantified. If one allows the spending amounts to have a component that evolves randomly across time, it is possible for the estimate to be smaller than its actual value.<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a></p>
</div>
<div id="additional-thoughts" class="section level3">
<h3>Additional Thoughts</h3>
<p>Method 2 of having a universal control group is actually a special case of the above problem, where the control group does not vary at all. Under the assumption that each treatment would have a positive effect, the estimated effect for each subsequent treatment would always be overstated.</p>
<p>Only method 3 would give us a sensible result across both periods of the treatment. Here’s a fun little exercise - try to implement a random sample on the second period after subsetting the population using the targeting rule. Do you get a result similar to the calculated ATT above?</p>
</div>
<div id="tldr" class="section level3">
<h3>TL;DR</h3>
<p>In short, when it comes to choosing a random control group in a policy evaluation setting with multiple treatments and periods, the best option is the simplest one. Random assignment always works, no need to over complicate things.</p>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>More accurately only mean independence is required.<a href="#fnref1" class="footnote-back">↩</a></p></li>
<li id="fn2"><p>Keeping only members that were present in the control group of the previous time period introduces a selection bias.<a href="#fnref2" class="footnote-back">↩</a></p></li>
</ol>
</div>

      </article>

      <ul class="pager blog-pager">
        
          <li class="previous">
            <a href="https://www.timlrx.com/2017/11/05/november-reflections/" data-toggle="tooltip" data-placement="top" title="November Reflections">&larr; Previous Post</a>
          </li>
        
        
          <li class="next">
            <a href="https://www.timlrx.com/2017/11/23/dashboard-2-0/" data-toggle="tooltip" data-placement="top" title="Dashboard 2.0">Next Post &rarr;</a>
          </li>
        
      </ul>

      

    </div>
  </div>
</div>

    <footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <ul class="list-inline text-center footer-links">
          
              <li>
                <a href="mailto:timothy.lin@alumni.ubc.ca" title="Email me">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="https://github.com/timlrx" title="GitHub">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="https://linkedin.com/in/timothy-lin-0600ba141" title="LinkedIn">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
          
          <li>
            <a href="https://www.timlrx.com/index.xml" title="RSS">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-rss fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          
        </ul>
        <p class="credits copyright text-muted">
          Timothy Lin
          &nbsp;&bull;&nbsp;
          2018

          
            &nbsp;&bull;&nbsp;
            <a href="https://www.timlrx.com/">Quasilinear Musings</a>
          
        </p>
        
        <p class="credits theme-by text-muted">
          <a href="http://gohugo.io">Hugo v0.30.2</a> powered &nbsp;&bull;&nbsp; Theme by <a href="http://deanattali.com/beautiful-jekyll/">Beautiful Jekyll</a> adapted to <a href="https://github.com/halogenica/beautifulhugo">Beautiful Hugo</a>
          
        </p>
      </div>
    </div>
  </div>
</footer>

<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.js" integrity="sha384-/y1Nn9+QQAipbNQWU65krzJralCnuOasHncUFXGkdwntGeSvQicrYkiUBwsgUqc1" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/contrib/auto-render.min.js" integrity="sha384-dq1/gEHSxPZQ7DdrM82ID4YVol9BYyU7GbWlIwnwyPzotpoc57wDw/guX8EaYGPx" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://www.timlrx.com/js/main.js"></script>
<script src="https://www.timlrx.com/js/highlight.min.js"></script>
<script> hljs.initHighlightingOnLoad(); </script>
<script> renderMathInElement(document.body); </script>






  </body>
</html>

