---
title: "SG-Dashboard"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    mathjax: NULL
    self_contained: FALSE
---

```{r setup, include=FALSE}
library(flexdashboard)
knitr::opts_chunk$set(warning=FALSE, message=FALSE, cache=FALSE)
plotly_mod_dep = function(p){
  deps <- p$dependencies
  deps_urls <- purrr::map(
    deps,
    ~if(.x$name == "plotly-basic") {
      .x$src = list(file=getwd())
      .x$script = "plotly-redirect-cdn-1.49.4.js"
      .x
    } else {
      .x
    }
  )
  p$dependencies <- deps_urls
  p
}
```

```{r prelim, include=FALSE}
library(dplyr)
library(reshape2)
library(ggplot2)
library(gridExtra)
library(knitr)
library(kableExtra)
library(plotly)

### Find most recent file
file_path <- "C:/Users/Timot/Documents/Repo/sg-econ-api/data/gdp/"
files <- list.files(file_path)
date_list <- gsub("(.+)(-gdp.RData)","\\1",files)
recent_date <- date_list[order(format(as.Date(date_list),"%Y-%m-%d"))[length(date_list)]]
recent_date2 <- date_list[order(format(as.Date(date_list),"%Y-%m-%d"))[length(date_list)-1]]

load(paste(file_path,recent_date,"-gdp.RData", sep=""))
gdp <- va.sector.comb
gdp <- filter(gdp, year >= 2000)
load(paste(file_path,recent_date2,"-gdp.RData", sep=""))
gdp2 <- va.sector.comb
gdp2 <- filter(gdp2, year >= 2000)

#### Load Emp data
file_path <- "C:/Users/Timot/Documents/Repo/sg-econ-api/data/employment/"
files <- list.files(file_path)
date_list <- gsub("(.+)(-emp.RData)","\\1",files)
recent_date <- date_list[order(format(as.Date(date_list),"%Y-%m-%d"))[length(date_list)]]
load(paste(file_path,recent_date,"-emp.RData", sep=""))
```

```{r emp-data, include=FALSE}
###Employment graphs
latest_quarter <- emp$quarter[dim(emp)[1]]

ytd_emp <- emp %>% 
           filter(quarter == latest_quarter)

overall_change_emp <- emp %>%
  filter(year >= 2000 & industry=="Overall Economy") %>%
  mutate(period_lab=ifelse(quarter!="Q1","",period))
```


GDP
=====================================  

Row
-----------------------------------------------------------------------
### Trend in Overall GDP (QOQ)

```{r overallgdpqoq, echo=FALSE}
# Plot aggregate trend over the last 4 years
overall_gdp <- gdp %>%
               filter(industry=="Overall Economy") %>%
               top_n(16, wt=period)

overall_qoq <- ggplot(overall_gdp, aes(period, qoqsaa, group=1)) +
  geom_point() +
  geom_line() +
  geom_hline(yintercept = 0, linetype=2) +
  ylab("QoQ SA (%)") +
  xlab("") +
  theme_classic() +
  theme(axis.text.x=element_text(angle=45,hjust=1,vjust=1))

ggplotly(overall_qoq, tooltip=c("y","x")) %>%
  layout(margin = list(b = 80)) %>%
  partial_bundle()
```


### Trend in Overall GDP (YOY)

```{r overallgdpyoy, echo=FALSE}
overall_yoy <- ggplot(overall_gdp, aes(period, yoy, group=1)) +
  geom_point() +
  geom_line() +
  geom_hline(yintercept = 0, linetype=2) +
  ylab("YoY (%)") +
  xlab("") +
  theme_classic() +
  theme(axis.text.x=element_text(angle=45,hjust=1,vjust=1))

ggplotly(overall_yoy, tooltip=c("y","x")) %>%
  layout(margin = list(b = 80)) %>%
  partial_bundle()
```

Row
-----------------------------------------------------------------------

### Industry growth

```{r indgrowth, echo=FALSE}
ind_growth <- gdp %>%
  filter(industry!="Other Goods Industries" & industry!="Other Services Industries" ) %>%
  top_n(1, wt=period) %>%
  melt(measure.vars=c("yoy","qoqsaa"), value.name="growth", variable.name="series") %>%
  arrange(industry)

ind_growth$industry.short <- factor(ind_growth$industry.short,
                                    levels=rev(levels(ind_growth$industry.short)))

sector.bar <- ggplot(ind_growth, aes(industry.short, growth)) +
  geom_col(aes(fill=series), position=position_dodge(width=1)) +
  ylab("Growth (%)") +
  xlab("") +
  theme(axis.text.x=element_text(angle=45,hjust=1,vjust=1),
        axis.title.x=element_blank()) +
  theme_classic() + 
  coord_flip()

plotly_build(sector.bar) %>%
  layout(margin = list(l = 150)) %>%
  partial_bundle()

```


Row
-----------------------------------------------------------------------


### Number of consecutive -ve / +ve quarters of YoY growth

```{r gdpstreak, results="asis", echo=FALSE}
count_streak <- function(x){ tmp<-cumsum(x);tmp-cummax((!x)*tmp)}

va_streak <- gdp %>%
  filter(industry!="Other Goods Industries" & industry!="Other Services Industries" ) %>%
  group_by(industry) %>% 
  filter(year > 2000) %>%
  mutate(neg_yoy = yoy < 0,
         pos_yoy = yoy > 0,
         neg_yoy_streak = count_streak(neg_yoy),
         pos_yoy_streak = count_streak(pos_yoy)) %>%
  ungroup() %>%
  top_n(10, wt=period) %>%
  select(industry, neg_yoy_streak, pos_yoy_streak) %>%
  arrange(industry)

va_streak$industry <- as.character(va_streak$industry)
# va_streak$industry <- gsub("&", "and", va_streak$industry)

colnames(va_streak) <- c("Industry", " -ve ", " +ve ")

kable(va_streak, format="html") %>% kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```

### Top 3 data revisions from last quarter (`r gdp2$period[dim(gdp2)[1]]`)

```{r revision, results="asis", echo=FALSE}

revision_period <- gdp2$period[dim(gdp2)[1]]

#### Take the previous quarter
updated_va <- gdp %>%
  filter(industry!="Other Goods Industries" & industry!="Other Services Industries" ) %>%
  top_n(20, wt=period) %>%
  filter(row_number() <= 10) %>%
  select(industry, yoy) %>%
  rename(updated_yoy = yoy)

#### Compare against last quarter's data
old_va <- gdp2 %>%
  filter(industry!="Other Goods Industries" & industry!="Other Services Industries" ) %>%
  top_n(10, wt=period) %>%
  select(industry, yoy) %>%
  rename(old_yoy = yoy)

#### Take overall economy and 3 biggest revisions
compare_tbl <- updated_va %>%
               inner_join(old_va, by="industry") %>%
               mutate(revision = updated_yoy - old_yoy,
                      abs_revision = abs(revision)) %>%
               arrange(desc(abs_revision)) %>%
               select(industry, updated_yoy, revision) %>%
               filter(industry=="Overall Economy" |
                      row_number() <= 3)

colnames(compare_tbl) <- c("Industry", "Updated YoY growth (%)", "Revision (% pt)")

kable(compare_tbl, digits=2, format="html") %>% kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```


Row
-----------------------------------------------------------------------
### Source
Data extracted from SingStat's API. Updated based on `r gdp$period[dim(gdp)[1]]` results downloaded on `r recent_date`.

Employment
=====================================     

Row
-----------------------------------------------------------------------

### Overall Change in employment since 2000

```{r overall-emp, echo=FALSE}
overall_emp <- ggplot(overall_change_emp, aes(period, pct_change_emp, group=industry)) +
  geom_point() +
  geom_line() +
  geom_hline(yintercept = 0, linetype=2) +
  ylab("YoY change in employment (%)") +
  xlab("") +
  scale_x_discrete(breaks=overall_change_emp$period_lab) +
  theme_classic() +
  theme(axis.text.x=element_text(angle=45,hjust=1,vjust=1))

ggplotly(overall_emp, tooltip=c("y","x")) %>%
  layout(margin = list(b = 80)) %>%
  partial_bundle()
```

Row
-----------------------------------------------------------------------

### Industry employment trends

```{r empind, echo=FALSE}
pct_change_emp <- emp %>%
    filter(year >= 2014 & industry.short!="Overall" & industry.short!="Other Ser") %>%
    mutate(industry2 = industry) %>%
    ggplot(aes(period, pct_change_emp, group=industry2, color=industry)) +
           geom_point() +
           geom_line() +
           geom_hline(yintercept = 0, linetype=2) +
           ylab("YoY change in employment (%)") +
           xlab("") +
           theme_classic() +
           theme(axis.text.x=element_text(angle=45,hjust=1,vjust=1))

ggplotly(pct_change_emp, tooltip=c("period","pct_change_emp", "industry")) %>%
  layout(margin = list(b = 80),
         legend = list(orientation = 'h',xanchor = "center", yanchor="bottom", y=-0.5)) %>%
  partial_bundle()
```

Row
-----------------------------------------------------------------------

### Change in employment since 2010

```{r emp-ind-year, echo=FALSE}
change_emp_year <- ytd_emp %>%
  filter(industry.short!="Overall" & industry.short!="Other Ser") %>%
  filter(year >= 2011) %>%
  mutate(year = factor(year), change_emp = change_emp/1000) %>%
  arrange(desc(year))

change_emp_year$industry.short <- factor(change_emp_year$industry.short,
                                    levels=rev(levels(change_emp_year$industry.short)))

change_emp_year_plot <- change_emp_year %>% 
  ggplot(aes(x=industry.short)) +
  geom_col(aes(y = change_emp, fill = year),  
           position = position_stack(reverse = TRUE)) +
  coord_flip() +
  ylab("Change in Employment (thousands)") +
  xlab("") +
  scale_y_continuous(breaks=c(-40,-20,0,20,40,60,80,100)) +
  theme_classic() 

ggplotly(change_emp_year_plot) %>%
  layout(margin = list(l = 150)) %>%
  partial_bundle()
```
